/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute } from 'workbox-precaching';
import { BackgroundSyncPlugin } from 'workbox-background-sync';
import { registerRoute } from 'workbox-routing';
import { NetworkOnly } from 'workbox-strategies';

declare let self: ServiceWorkerGlobalScope;

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

self.skipWaiting();
clientsClaim();

// Background Sync Queue
const bgSyncPlugin = new BackgroundSyncPlugin('sync-tickets', {
  maxRetentionTime: 24 * 60, // Retry for max of 24 Hours (specified in minutes)
});

// Intercept push to /api/sync/push to queue it
registerRoute(
  /\/api\/sync\/push/,
  new NetworkOnly({
    plugins: [bgSyncPlugin],
  }),
  'POST'
);

// Push Event for Notifications
self.addEventListener('push', (event) => {
  if (event.data) {
    const data = event.data.json();
    
    const title = data.title || 'NPrep QMS';
    const options: NotificationOptions = {
      body: data.body || 'You have a new update on your ticket.',
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      vibrate: [100, 50, 100],
      data: {
        url: data.url || '/',
      },
    };

    event.waitUntil(self.registration.showNotification(title, options));
  }
});

// Notification Click
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  if (event.notification.data && event.notification.data.url) {
    event.waitUntil(
      self.clients.openWindow(event.notification.data.url)
    );
  }
});

// Listen for sync event manually if we want Dexie logic
self.addEventListener('sync', (event: SyncEvent) => {
  if (event.tag === 'sync-tickets') {
    event.waitUntil(
      (async () => {
        // Trigger a message to the client to do the Dexie sync, 
        // or since SW doesn't easily access Dexie in all setups, 
        // we handle sync inside workbox queue or via app client.
        const clients = await self.clients.matchAll();
        clients.forEach(client => {
          client.postMessage({ type: 'SYNC_TICKETS' });
        });
      })()
    );
  }
});
